### PR TITLE
User model added by SanyamAgrawal07

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 6

#### Short description of what this resolves:

Added the user schema setting name and email as required fields and verified by default as false following mongoose schema structure

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Replace ObjectId with `Schema.Types.ObjectId`

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Yes sorry my bad. I had a doubt whenever changes are requested in a PR do we need to create a new PR or we can just make changes in this one(if that is possible somehow).

**Comment by BuddyLongLegs** [comment]
You can change in this PR itself, no need to create a new PR.

**Comment by BuddyLongLegs** [comment]
Just push in your forked repo, this PR will update automatically

**Review by BuddyLongLegs — APPROVED** [review]
Great Work!

**Pull request merged**
