### PR TITLE
createForm function added

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 87

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
HasFileField and HasRecaptcha may be `false` which will also send bad response. Send bad response only when these fields are not in `request.body`

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs I have made a change please check

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
name cannot be `""`

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs yep done

**Review by BuddyLongLegs — APPROVED** [review]

**Pull request merged**
