### PR TITLE
updateUser function added in userController.js

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 61

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Sorry there has been change in plans regarding this function. You'll just need to change the User's name and email if the password is verified. Please verify the updated request structure [here](https://github.com/opencodeiiita/SaveMyForm-Backend/blob/main/API_Endpoints.md#update). If the password saved in the database is an empty string then return a bad response that `"You will need to create a password before changing these settings"`

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Please review the changes made

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Verify that the new email is a vaild email or not before saving changes

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Added email validation using validator library and no field is updated if the email is invalid

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
More change in plans, Add recaptcha verification too

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Added recaptcha verification

**Review by BuddyLongLegs — APPROVED** [review]
Good Work!

**Pull request merged**
