### PR TITLE
Project Dashboard

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 78

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
You should not put project.is_owner field in the lines 35 and 36 by yourself. Implement that in the .project() function dynamically.

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs plz review the changes

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Remove is_owner: 1 line

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs removed

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Replace `"$req.user._id"` with "req.user._id" (not in double quotes)

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs yep done

**Comment by BuddyLongLegs** [comment]
What's that for loop doing? You can implement form submission count and latest form submission dynamically.

**Pull request closed without merging**
