### PR TITLE
Create JWT

### PR DESCRIPTION
**Pull request by vedant-z**
Issue: 17

#### Short description of what this resolves:
Creates a function to create JWT token from JavaScript Object.

#### Changes proposed in this pull request and/or Screenshots of changes:

- Function takes JavaScript Object as an argument and returns a string which is a JWT token for that Object.

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
You put a lot of effort into this task, and I appreciate that. But to keep the code readable and understandable use [this](https://www.npmjs.com/package/jsonwebtoken) library for creating JWTs. You are free to install this library.

**Comment by BuddyLongLegs** [comment]
@vedant-z please use the above library for creating JWT tokens

**Comment by vedant-z** [comment]
@BuddyLongLegs Ua I got your point. Working on it

**Comment by vedant-z** [comment]
@BuddyLongLegs Please check if the required changes are made correctly or are there any more changes

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
It's an ejs module so import using: `import jwt from 'jsonwebtoken';` and set the expiry to `30d`, i.e., 30 days. These are final changes, then I'll merge your PR.

**Comment by vedant-z** [comment]
@BuddyLongLegs DONE ^**^

**Review by BuddyLongLegs — APPROVED** [review]
Great Work!

**Pull request merged**
