### PR TITLE
getVerificationLink function added in userController

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 58

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
The email should only be sent if the user is not verified. Also please test if `req.socket.remoteAddress` will work or not, you can use req.ip too.

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs Please review now

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Return a 200 status response at the end of the function or else, the call will never end

**Comment by SanyamAgrawal07** [comment]
Please tell me what should I keep the response message as? 'User verified' or 'Verification mail sent'?

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs please check now

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Function should return bad response if user is already verified

**Comment by SanyamAgrawal07** [comment]
@BuddyLongLegs yes fixed that

**Review by BuddyLongLegs — APPROVED** [review]
Good work!

**Pull request merged**
