### PR TITLE
deleteFormController

### PR DESCRIPTION
**Pull request by Vishesh-Vijay**
Issue: 116

#### 
image

### CODE REVIEW

**Comment by BuddyLongLegs** [comment]
Please add it in the form routes

**Comment by Vishesh-Vijay** [comment]
i've changed it you can check now

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Collaborators are not allowed to delete form,

**Comment by Vishesh-Vijay** [comment]
changes done as asked you can review it now

**Review by BuddyLongLegs — APPROVED** [review]

**Pull request merged**
