### PR TITLE
Update project.model.js

### PR DESCRIPTION
**Pull request by vedant-z**
Issue: 7 

#### Short description of what this resolves:
Creates a Project model

#### Changes proposed in this pull request and/or Screenshots of changes:

- Created a Project model
image

### CODE REVIEW

**Comment by BuddyLongLegs** [comment]
Remove the # sign in the PR message

**Comment by vedant-z** [comment]
@BuddyLongLegs I hope it's cleared now

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
There a few issues with this code:
- The type of owner should be ObjectId only instead of array of object I'd.
- The type of collaborators should be Array of objectIds with ref to User
- the type of forms should be Array of ObjectIds with ref to Form
- type of Allowed Origins should array of strings
- generate a random 16 length string as default for id

Try to add basic validations in all the fields

**Comment by vedant-z** [comment]
@BuddyLongLegs  I didn't understood the last point. What needs to be done exactly?

**Comment by BuddyLongLegs** [comment]
> @BuddyLongLegs I didn't understood the last point (Random 16 length string). What needs to be done exactly?

The default value of Id should be a function that returns a randomly generated 16-length string.

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
Change the User and Form refs to `'user'` and `'form'` (all lower case), Sorry for not telling you earlier.

**Comment by vedant-z** [comment]
@BuddyLongLegs Have I done the required changes correctly? Let me know if there are any more changes to be made.

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
There is no need of importing User and Form, remove that, and if you can format the code using prettier(vs code extension) that would be amazing. Everything else seems fine. I will merge after these minor changes.

**Review by BuddyLongLegs — CHANGES_REQUESTED** [review]
remove curly braces around the function on line number 22.

**Review by BuddyLongLegs — APPROVED** [review]
Great Work @vedant-z

**Pull request merged**
